/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_j99_library_mp3recorder_LameEncoder */

#ifndef _Included_io_j99_library_mp3recorder_LameEncoder
#define _Included_io_j99_library_mp3recorder_LameEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_j99_library_mp3recorder_LameEncoder
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_io_j99_library_mp3recorder_LameEncoder_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     io_j99_library_mp3recorder_LameEncoder
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_io_j99_library_mp3recorder_LameEncoder_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     io_j99_library_mp3recorder_LameEncoder
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_io_j99_library_mp3recorder_LameEncoder_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     io_j99_library_mp3recorder_LameEncoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_j99_library_mp3recorder_LameEncoder_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
